"""Add tender notes table

Revision ID: 03ecc7e7cb84
Revises: 
Create Date: 2025-05-28 22:12:11.614916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ecc7e7cb84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender_notes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
